##
## File:        Makefile.config.in
## Copyrights:  (c) 2005 The Trustees of Princeton University and Board of
##                  Regents of the University of Texas.  All rights reserved.
##              (c) 2009 Kevin T. Chu.  All rights reserved.
## Revision:    $Revision$
## Modified:    $Date$
## Description: configuration file for level set method library Makefiles
##


# include and lib directories
LSMLIB_INCLUDE = $(BUILD_DIR)/include
LSMLIB_LIB_DIR = $(BUILD_DIR)/lib 
LSMLIB_LIBS    =  -llsm_serial -llsm_toolbox  -lm


# Pattern Rules
%.o: %.c
	gcc -c -O3 -funroll-loops -fPIC -g -O2 -I$(LSMLIB_INCLUDE) $(CFLAGS) $(CPPFLAGS) $(CFLAGS_EXTRA) -o $@ $<

%.o: %.c %.h
	gcc -c -O3 -funroll-loops -fPIC -g -O2 -I$(LSMLIB_INCLUDE) $(CFLAGS) $(CPPFLAGS) $(CFLAGS_EXTRA) -o $@ $<

%.o: %.f
	gfortran -c -O3 -funroll-loops -fPIC -fdefault-real-8 -fdefault-double-8 -g -O2 $(FFLAGS) $(FFLAGS_EXTRA) -o $@ $<

%.o: %.cc
	g++ -c -O3 -funroll-loops -fPIC -fno-implicit-templates -g -O2 -I$(LSMLIB_INCLUDE) $(CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS_EXTRA) -o $@ $<

%.o: %.cc %.h
	g++ -c -O3 -funroll-loops -fPIC -fno-implicit-templates -g -O2 -I$(LSMLIB_INCLUDE) $(CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS_EXTRA) -o $@ $<

%.o: %.C
	g++ -c -O3 -funroll-loops -fPIC -fno-implicit-templates -g -O2 -I$(LSMLIB_INCLUDE) $(CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS_EXTRA) -o $@ $<

%.o: %.C %.h
	g++ -c -O3 -funroll-loops -fPIC -fno-implicit-templates -g -O2 -I$(LSMLIB_INCLUDE) $(CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS_EXTRA) -o $@ $<
